identifier: l6d7j0l9107fz4w3
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-blog
homeFolder: C:\Users\Luis_DEV\Documents\MyTechProjects\my-blog
distFolder: dist/my-blog
outDir: C:\Users\Luis_DEV\Documents\MyTechProjects\my-blog\dist\static
handle404: ''
allowErrorCollect: true
